# Generated by Django 5.2.5 on 2025-08-22 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('sqft_living', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(15000)])),
                ('sqft_lot', models.IntegerField(validators=[django.core.validators.MinValueValidator(500), django.core.validators.MaxValueValidator(2000000)])),
                ('floors', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(3.5)])),
                ('waterfront', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('yr_built', models.IntegerField(validators=[django.core.validators.MinValueValidator(1934), django.core.validators.MaxValueValidator(2014)])),
                ('sqft_above', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15000)])),
                ('sqft_basement', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5000)])),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12'), (13, 'Grade 13')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)])),
                ('view', models.IntegerField(choices=[(0, 'View 0'), (1, 'View 1'), (2, 'View 2'), (3, 'View 3'), (4, 'View 4')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)])),
                ('condition', models.IntegerField(choices=[(1, 'Condition 1'), (2, 'Condition 2'), (3, 'Condition 3'), (4, 'Condition 4'), (5, 'Condition 5')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('house_renovated', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('long', models.FloatField(validators=[django.core.validators.MinValueValidator(-122.5), django.core.validators.MaxValueValidator(-121.3)])),
                ('lat', models.FloatField(validators=[django.core.validators.MinValueValidator(47.1), django.core.validators.MaxValueValidator(47.8)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'House Prediction',
                'verbose_name_plural': 'House Predictions',
                'ordering': ['-created_at'],
            },
        ),
    ]
